name: Python Tests

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  unit:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python_version: ['3.10', '3.11', '3.12', '3.13']
        resolution: [lowest-direct, highest]
    steps:
    - uses: actions/checkout@v4
    - name: Setup venv
      uses: ./.github/actions/setup-venv
      with:
        python-version: ${{ matrix.python_version }}
        resolution: ${{ matrix.resolution }}
    - name: Run tests
      id: run-tests
      run: >
        uv run pytest 
          --junitxml=pytest.xml \
          --cov-report=term-missing:skip-covered \
          --cov-report=xml:coverage.xml \
          --cov=src tests \
          --log-level=DEBUG \
          --verbose
      shell: bash 
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true

  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup venv
      uses: ./.github/actions/setup-venv
      with:
        only-dev: true
    - name: Ruff format
      run: uv run ruff format --check
    - name: Ruff check
      run: uv run ruff check

  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup venv
      uses: ./.github/actions/setup-venv
    - run: |
        uv run mypy .

  deptry:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup venv
      uses: ./.github/actions/setup-venv
    - run: |-
        uv run deptry ./src
